server:
  port: 9005
spring:
  redis:
    host: 47.98.206.89
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 1
        time-between-eviction-runs: 10s
  jpa:
    hibernate:
      ddl-auto: create
    open-in-view: false
  datasource:
    username: pan_back
    password: F6my6acdmNxJKknG
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.98.206.89:3306/pan_back
  jackson:
    default-property-inclusion: non_null
  servlet:
    multipart:
      max-file-size: 2048MB
      max-request-size: 2048MB
mybatis:
  type-aliases-package: com.example.panbackend.entity.po
logging:
  level:
    com.example.pan_back_end: debug
sa-token:
  is-log: true
  timeout: 2592000
  token-style: simple-uuid
  token-name: token
  is-share: true
  is-concurrent: false
const:
  share:
    key_file_pre: "key_to_file:"
    file_key_pre: "file_to_key:"
    file_path: "file_path"
    file_time: "file_time"
  air_drop:
    air_drop_ttl: 60
    air_drop_user_id: -1
